from ida_name import set_name
from base_types import Ident

funcs = [
	# diabpsx/psxsrc/presonly.cpp
	Ident(addr=0x80139BFC, name="PresOnlyTestRoutine__Fv", decl="void PresOnlyTestRoutine__Fv()"),

	# diabpsx/psxsrc/fe.cpp
	Ident(addr=0x80139C24, name="FeInitBuffer__Fv", decl="void FeInitBuffer__Fv()"),
	Ident(addr=0x80139C50, name="FeAddEntry__Fii8TXT_JUSTUsP7FeTableP5CFont", decl="void FeAddEntry__Fii8TXT_JUSTUsP7FeTableP5CFont(int X, int Y, enum TXT_JUST Just, unsigned short Str, struct FeTable *MenuPtr, struct CFont *Font)"),
	Ident(addr=0x80139CD4, name="FeAddTable__FP11FeMenuTablei", decl="void FeAddTable__FP11FeMenuTablei(struct FeMenuTable *Table, int Count)"),
	Ident(addr=0x80139D50, name="FeAddNameTable__FPUci", decl="void FeAddNameTable__FPUci(unsigned char *Table, int Count)"),
	Ident(addr=0x80139E78, name="FeDrawBuffer__Fv", decl="void FeDrawBuffer__Fv()"),
	Ident(addr=0x8013A4A4, name="FeNewMenu__FP7FeTable", decl="void FeNewMenu__FP7FeTable(struct FeTable *Menu)"),
	Ident(addr=0x8013A524, name="FePrevMenu__Fv", decl="void FePrevMenu__Fv()"),
	Ident(addr=0x8013A66C, name="FeSelUp__Fi", decl="void FeSelUp__Fi(int No)"),
	Ident(addr=0x8013A754, name="FeSelDown__Fi", decl="void FeSelDown__Fi(int No)"),
	Ident(addr=0x8013A83C, name="FeGetCursor__Fv", decl="int FeGetCursor__Fv()"),
	Ident(addr=0x8013A850, name="FeSelect__Fv", decl="void FeSelect__Fv()"),
	Ident(addr=0x8013A8A0, name="FeMainKeyCtrl__FP7CScreen", decl="void FeMainKeyCtrl__FP7CScreen(struct CScreen *FeScreen)"),
	Ident(addr=0x8013AA68, name="InitDummyMenu__Fv", decl="void InitDummyMenu__Fv()"),
	Ident(addr=0x8013AA70, name="InitFrontEnd__FP9FE_CREATE", decl="void InitFrontEnd__FP9FE_CREATE(struct FE_CREATE *CreateStruct)"),
	Ident(addr=0x8013ABA4, name="FeInitMainMenu__Fv", decl="void FeInitMainMenu__Fv()"),
	Ident(addr=0x8013AC20, name="FeInitNewGameMenu__Fv", decl="void FeInitNewGameMenu__Fv()"),
	Ident(addr=0x8013ACB0, name="FeNewGameMenuCtrl__Fv", decl="void FeNewGameMenuCtrl__Fv()"),
	Ident(addr=0x8013AE64, name="FeInitPlayer1ClassMenu__Fv", decl="void FeInitPlayer1ClassMenu__Fv()"),
	Ident(addr=0x8013AEE8, name="FeInitPlayer2ClassMenu__Fv", decl="void FeInitPlayer2ClassMenu__Fv()"),
	Ident(addr=0x8013AF6C, name="FePlayerClassMenuCtrl__Fv", decl="void FePlayerClassMenuCtrl__Fv()"),
	Ident(addr=0x8013AFB4, name="FeDrawChrClass__Fv", decl="void FeDrawChrClass__Fv()"),
	Ident(addr=0x8013B43C, name="FeInitNewP1NameMenu__Fv", decl="void FeInitNewP1NameMenu__Fv()"),
	Ident(addr=0x8013B498, name="FeInitNewP2NameMenu__Fv", decl="void FeInitNewP2NameMenu__Fv()"),
	Ident(addr=0x8013B4EC, name="FeNewNameMenuCtrl__Fv", decl="void FeNewNameMenuCtrl__Fv()"),
	Ident(addr=0x8013BAB4, name="FeCopyPlayerInfoForReturn__Fv", decl="void FeCopyPlayerInfoForReturn__Fv()"),
	Ident(addr=0x8013BBC8, name="FeEnterGame__Fv", decl="void FeEnterGame__Fv()"),
	Ident(addr=0x8013BBF0, name="FeInitLoadMemcardSelect__Fv", decl="void FeInitLoadMemcardSelect__Fv()"),
	Ident(addr=0x8013BC70, name="FeInitLoadChar1Menu__Fv", decl="void FeInitLoadChar1Menu__Fv()"),
	Ident(addr=0x8013BCD8, name="FeInitLoadChar2Menu__Fv", decl="void FeInitLoadChar2Menu__Fv()"),
	Ident(addr=0x8013BD48, name="FeInitDifficultyMenu__Fv", decl="void FeInitDifficultyMenu__Fv()"),
	Ident(addr=0x8013BDEC, name="FeDifficultyMenuCtrl__Fv", decl="void FeDifficultyMenuCtrl__Fv()"),
	Ident(addr=0x8013BED0, name="FeInitBackgroundMenu__Fv", decl="void FeInitBackgroundMenu__Fv()"),
	Ident(addr=0x8013BF1C, name="FeInitBook1Menu__Fv", decl="void FeInitBook1Menu__Fv()"),
	Ident(addr=0x8013BF6C, name="FeInitBook2Menu__Fv", decl="void FeInitBook2Menu__Fv()"),
	Ident(addr=0x8013BFBC, name="FeBackBookMenuCtrl__Fv", decl="void FeBackBookMenuCtrl__Fv()"),
	Ident(addr=0x8013C200, name="PlayDemo__Fv", decl="void PlayDemo__Fv()"),
	Ident(addr=0x8013C214, name="FadeFEOut__Fv", decl="void FadeFEOut__Fv()"),
	Ident(addr=0x8013C2D8, name="DrawBackTSK__FP4TASK", decl="void DrawBackTSK__FP4TASK(struct TASK *T)"),
	Ident(addr=0x8013C460, name="FeInitMainStuff__FP4TASK", decl="void FeInitMainStuff__FP4TASK(struct TASK *T2)"),
	Ident(addr=0x8013C50C, name="FrontEndTask__FP4TASK", decl="void FrontEndTask__FP4TASK(struct TASK *T)"),
	Ident(addr=0x8013C9B8, name="DrawFeTwinkle__Fii", decl="void DrawFeTwinkle__Fii(int TwinkX, int TwinkY)"),

	# diabpsx/psxsrc/credits.cpp
	Ident(addr=0x8013D1B4, name="InitCredits__Fv", decl="void InitCredits__Fv()"),
	Ident(addr=0x8013D248, name="PrintCredits__Fiiiiii", decl="int PrintCredits__Fiiiiii(int StrNo, int Y, int CharFade, int RFlag, int GFlag, int BFlag)"),
	Ident(addr=0x8013DA78, name="DrawCreditsTitle__Fiiiii", decl="void DrawCreditsTitle__Fiiiii(int TitleNo, int TitleFade, int TitleMode, int NextTitleNo, int Y)"),
	Ident(addr=0x8013DB30, name="DrawCreditsSubTitle__Fiiiii", decl="void DrawCreditsSubTitle__Fiiiii(int SubTitleNo, int SubTitleFade, int SubTitleMode, int NextSubTitleNo, int Y)"),
	Ident(addr=0x8013DBE8, name="CredCountNL__Fi", decl="int CredCountNL__Fi(int Str)"),
	Ident(addr=0x8013DC54, name="DoCredits__Fv", decl="void DoCredits__Fv()"),

	# diabpsx/psxsrc/memcard.cpp
	Ident(addr=0x801426F8, name="endian_swap__FPUci", decl="void endian_swap__FPUci(unsigned char *b, int byts)"),
	Ident(addr=0x8014272C, name="sjis_endian_swap__FPUci", decl="void sjis_endian_swap__FPUci(unsigned char *b, int byts)"),
	Ident(addr=0x80142774, name="to_sjis__Fc", decl="unsigned short to_sjis__Fc(char asc)"),
	Ident(addr=0x801427F4, name="to_ascii__FUs", decl="char to_ascii__FUs(unsigned short sjis)"),
	Ident(addr=0x8014287C, name="ascii_to_sjis__FPUcPUs", decl="void ascii_to_sjis__FPUcPUs(unsigned char *asc, unsigned short *sjis)"),
	Ident(addr=0x80142904, name="is_sjis__FPUc", decl="int is_sjis__FPUc(unsigned char *buf)"),
	Ident(addr=0x80142910, name="sjis_to_ascii__FPUsPc", decl="int sjis_to_ascii__FPUsPc(unsigned short *sjis, char *asc)"),
	Ident(addr=0x80142998, name="read_card_directory__Fi", decl="void read_card_directory__Fi(int card_number)"),
	Ident(addr=0x80142BF4, name="test_card_format__Fi", decl="int test_card_format__Fi(int card_number)"),
	Ident(addr=0x80142CE4, name="checksum_data__FPci", decl="int checksum_data__FPci(char *buf, int size)"),
	Ident(addr=0x80142D20, name="delete_card_file__Fii", decl="int delete_card_file__Fii(int card_number, int file)"),
	Ident(addr=0x80142E18, name="read_card_file__FiiiPc", decl="int read_card_file__FiiiPc(int card_number, int file, int id, char *buf)"),
	Ident(addr=0x80142FF4, name="format_card__Fi", decl="int format_card__Fi(int card_number)"),
	Ident(addr=0x801430B8, name="write_card_file__FiiPcT2PUcPUsiT4", decl="int write_card_file__FiiPcT2PUcPUsiT4(int card_number, int id, char *name, char *title, unsigned char *icon, unsigned short *clut, int size, unsigned char *buf)"),
	Ident(addr=0x8014340C, name="new_card__Fi", decl="void new_card__Fi(int card_number)"),
	Ident(addr=0x801434A0, name="service_card__Fi", decl="void service_card__Fi(int card_number)"),

	# diabpsx/psxsrc/dlg.cpp
	Ident(addr=0x80159590, name="GetFileNumber__FiPc", decl="int GetFileNumber__FiPc(int side, char *file_name)"),
	Ident(addr=0x80159650, name="DoSaveOptions__Fv", decl="int DoSaveOptions__Fv()"),
	Ident(addr=0x80159678, name="DoSaveGame__Fv", decl="int DoSaveGame__Fv()"),
	Ident(addr=0x801597F0, name="DoLoadGame__Fv", decl="void DoLoadGame__Fv()"),
	Ident(addr=0x80159894, name="DoFrontEndLoadCharacter__Fi", decl="int DoFrontEndLoadCharacter__Fi(int slot)"),
	Ident(addr=0x801598EC, name="McInitLoadCard1Menu__Fv", decl="void McInitLoadCard1Menu__Fv()"),
	Ident(addr=0x8015992C, name="McInitLoadCard2Menu__Fv", decl="void McInitLoadCard2Menu__Fv()"),
	Ident(addr=0x8015996C, name="ChooseCardLoad__Fv", decl="void ChooseCardLoad__Fv()"),
	Ident(addr=0x80159A08, name="McInitLoadGameMenu__Fv", decl="void McInitLoadGameMenu__Fv()"),
	Ident(addr=0x80159A6C, name="McMainKeyCtrl__Fv", decl="void McMainKeyCtrl__Fv()"),
	Ident(addr=0x80159D08, name="McCharCardMenuCtrl__Fv", decl="void McCharCardMenuCtrl__Fv()"),
	Ident(addr=0x80159F50, name="McMainCharKeyCtrl__Fv", decl="void McMainCharKeyCtrl__Fv()"),
	Ident(addr=0x8015A3BC, name="ShowAlertBox__Fv", decl="void ShowAlertBox__Fv()"),
	Ident(addr=0x8015A5C8, name="GetLoadStatusMessage__FPc", decl="unknown GetLoadStatusMessage__FPc(char *file_name)"),
	Ident(addr=0x8015A67C, name="GetSaveStatusMessage__FiPc", decl="unknown GetSaveStatusMessage__FiPc(int fileblocks, char *file_name)"),
	Ident(addr=0x8015A79C, name="ShowGameFiles__FPciiG4RECTi", decl="void ShowGameFiles__FPciiG4RECTi(char *filename, int saveflag, int Spacing, struct RECT ORect, int yoff)"),
	Ident(addr=0x8015A90C, name="ShowCharacterFiles__FiiG4RECTi", decl="void ShowCharacterFiles__FiiG4RECTi(int cs, int Spacing, struct RECT ORect, int yoff)"),
	Ident(addr=0x8015AAEC, name="PackItem__FP12PkItemStructPC10ItemStruct", decl="void PackItem__FP12PkItemStructPC10ItemStruct(struct PkItemStruct *id, struct ItemStruct *is)"),
	Ident(addr=0x8015AB98, name="PackPlayer__FP14PkPlayerStructi", decl="void PackPlayer__FP14PkPlayerStructi(struct PkPlayerStruct *pPack, int pnum)"),
	Ident(addr=0x8015ADAC, name="UnPackItem__FPC12PkItemStructP10ItemStruct", decl="void UnPackItem__FPC12PkItemStructP10ItemStruct(struct PkItemStruct *is, struct ItemStruct *id)"),
	Ident(addr=0x8015AEE0, name="VerifyGoldSeeds__FP12PlayerStruct", decl="void VerifyGoldSeeds__FP12PlayerStruct(struct PlayerStruct *pPlayer)"),
	Ident(addr=0x8015AFB8, name="UnPackPlayer__FPC14PkPlayerStructiUc", decl="void UnPackPlayer__FPC14PkPlayerStructiUc(struct PkPlayerStruct *pPack, int pnum, unsigned char killok)"),
	Ident(addr=0x8015B284, name="ConstructSlotName__FPci", decl="void ConstructSlotName__FPci(char *TempStr, int slot)"),
	Ident(addr=0x8015B37C, name="GetSpinnerWidth__Fi", decl="int GetSpinnerWidth__Fi(int j)"),
	Ident(addr=0x8015B420, name="ReconstructSlotName__Fii", decl="char* ReconstructSlotName__Fii(int side, int file)"),

	# diabpsx/source/loadsave.cpp
	Ident(addr=0x8015B958, name="GetOptStr__Fv", decl="char* GetOptStr__Fv()"),
	Ident(addr=0x8015B968, name="GetDiabloStr__Fv", decl="char* GetDiabloStr__Fv()"),
	Ident(addr=0x8015B978, name="BLoad__Fv", decl="char BLoad__Fv()"),
	Ident(addr=0x8015B994, name="ILoad__Fv", decl="int ILoad__Fv()"),
	Ident(addr=0x8015B9E8, name="OLoad__Fv", decl="unsigned char OLoad__Fv()"),
	Ident(addr=0x8015BA0C, name="LoadQuest__Fi", decl="void LoadQuest__Fi(int i)"),
	Ident(addr=0x8015BAD4, name="BSave__Fc", decl="void BSave__Fc(char v)"),
	Ident(addr=0x8015BAEC, name="ISave__Fi", decl="void ISave__Fi(int v)"),
	Ident(addr=0x8015BB4C, name="OSave__FUc", decl="void OSave__FUc(unsigned char v)"),
	Ident(addr=0x8015BB90, name="SaveQuest__Fi", decl="void SaveQuest__Fi(int i)"),
	Ident(addr=0x8015BC5C, name="PSX_GM_SaveGame__FiPcT1", decl="int PSX_GM_SaveGame__FiPcT1(int card_number, char *name, char *title)"),
	Ident(addr=0x8015C1BC, name="PSX_GM_LoadGame__FUcii", decl="int PSX_GM_LoadGame__FUcii(unsigned char firstflag, int card_number, int file)"),
	Ident(addr=0x8015C2E8, name="PSX_CH_LoadGame__Fi", decl="void PSX_CH_LoadGame__Fi(int slot)"),
	Ident(addr=0x8015C388, name="PSX_CH_LoadBlock__Fii", decl="int PSX_CH_LoadBlock__Fii(int card_number, int file)"),
	Ident(addr=0x8015C3B0, name="PSX_CH_SaveGame__Fii", decl="int PSX_CH_SaveGame__Fii(int card_number, int slot)"),
	Ident(addr=0x8015C51C, name="RestorePads__Fv", decl="void RestorePads__Fv()"),
	Ident(addr=0x8015C5DC, name="StorePads__Fv", decl="void StorePads__Fv()"),
	Ident(addr=0x8015C698, name="GetIcon__Fv", decl="void GetIcon__Fv()"),
	Ident(addr=0x8015C6D4, name="PSX_OPT_LoadGame__Fiib", decl="int PSX_OPT_LoadGame__Fiib(int card_number, int file, unknown KillHandler)"),
	Ident(addr=0x8015C730, name="PSX_OPT_SaveGame__FiPc", decl="int PSX_OPT_SaveGame__FiPc(int card_number, char *filename)"),
	Ident(addr=0x8015C850, name="LoadOptions__Fv", decl="void LoadOptions__Fv()"),
	Ident(addr=0x8015C928, name="SaveOptions__Fv", decl="void SaveOptions__Fv()"),
	Ident(addr=0x8015C9CC, name="RestoreLoadedData__Fb", decl="int RestoreLoadedData__Fb(unknown firstflag)"),
]

for f in funcs:
	ida_name.set_name(f.addr, f.name)
