from ida_name import set_name
from base_types import Ident

funcs = [
	# diabpsx/psxsrc/fmv.cpp
	Ident(addr=0x80155E1C, name="_cd_seek", decl="void _cd_seek(int sec)"),
	Ident(addr=0x80155E54, name="init_cdstream", decl="void init_cdstream(int chunksize, unsigned char *buf, int bufsize)"),
	Ident(addr=0x80155E7C, name="flush_cdstream", decl="void flush_cdstream()"),
	Ident(addr=0x80155ED0, name="reset_cdstream", decl="void reset_cdstream()"),
	Ident(addr=0x80155F00, name="kill_stream_handlers", decl="void kill_stream_handlers()"),
	Ident(addr=0x80155F30, name="stream_cdready_handler", decl="void stream_cdready_handler(unsigned char status, unsigned char *result)"),
	Ident(addr=0x80156184, name="install_stream_handlers", decl="void install_stream_handlers()"),
	Ident(addr=0x801561C0, name="cdstream_service", decl="void cdstream_service()"),
	Ident(addr=0x801562B0, name="cdstream_get_chunk", decl="int cdstream_get_chunk(unsigned char **data, struct strheader **h)"),
	Ident(addr=0x801563C8, name="cdstream_is_last_chunk", decl="int cdstream_is_last_chunk()"),
	Ident(addr=0x801563E0, name="cdstream_discard_chunk", decl="void cdstream_discard_chunk()"),
	Ident(addr=0x80156500, name="close_cdstream", decl="void close_cdstream()"),
	Ident(addr=0x80156540, name="wait_cdstream", decl="void wait_cdstream()"),
	Ident(addr=0x801565F8, name="open_cdstream", decl="int open_cdstream(char *fname, int secoffs, int seclen)"),
	Ident(addr=0x80156720, name="set_mdec_img_buffer", decl="int set_mdec_img_buffer(unsigned char *p)"),
	Ident(addr=0x80156754, name="start_mdec_decode", decl="void start_mdec_decode(unsigned char *data, int x, int y, int w, int h)"),
	Ident(addr=0x801568B0, name="DCT_out_handler", decl="void DCT_out_handler()"),
	Ident(addr=0x80156960, name="init_mdec", decl="void init_mdec(unsigned char *vlc_buffer, unsigned char *vlc_table)"),
	Ident(addr=0x801569D0, name="init_mdec_buffer", decl="void init_mdec_buffer(char *buf, int size)"),
	Ident(addr=0x801569EC, name="split_poly_area", decl="int split_poly_area(struct POLY_FT4 *p, struct POLY_FT4 *bp, int offs, struct RECT *r, int sx, int sy, int correct)"),
	Ident(addr=0x80156DD4, name="rebuild_mdec_polys", decl="void rebuild_mdec_polys(int x, int y)"),
	Ident(addr=0x80156FA8, name="clear_mdec_frame", decl="void clear_mdec_frame()"),
	Ident(addr=0x80156FB4, name="draw_mdec_polys", decl="void draw_mdec_polys(int bright)"),
	Ident(addr=0x8015732C, name="invalidate_mdec_frame", decl="void invalidate_mdec_frame()"),
	Ident(addr=0x80157340, name="is_frame_decoded", decl="int is_frame_decoded()"),
	Ident(addr=0x8015734C, name="init_mdec_polys", decl="void init_mdec_polys(int x, int y, int w, int h, int bx1, int by1, int bx2, int by2, int correct)"),
	Ident(addr=0x801576DC, name="set_mdec_poly_bright", decl="void set_mdec_poly_bright(int br)"),
	Ident(addr=0x80157744, name="init_mdec_stream", decl="int init_mdec_stream(unsigned char *buftop, int sectors_per_frame, int mdec_frames_per_buffer)"),
	Ident(addr=0x80157794, name="init_mdec_audio", decl="void init_mdec_audio(int rate)"),
	Ident(addr=0x801578AC, name="kill_mdec_audio", decl="void kill_mdec_audio()"),
	Ident(addr=0x801578DC, name="stop_mdec_audio", decl="void stop_mdec_audio()"),
	Ident(addr=0x80157900, name="play_mdec_audio", decl="void play_mdec_audio(unsigned char *data, struct asec *h)"),
	Ident(addr=0x80157C34, name="set_mdec_audio_volume", decl="void set_mdec_audio_volume(short vol)"),
	Ident(addr=0x80157D00, name="resync_audio", decl="void resync_audio()"),
	Ident(addr=0x80157D10, name="stop_mdec_stream", decl="void stop_mdec_stream()"),
	Ident(addr=0x80157D54, name="dequeue_stream", decl="void dequeue_stream()"),
	Ident(addr=0x80157E40, name="dequeue_animation", decl="void dequeue_animation()"),
	Ident(addr=0x80157FF0, name="decode_mdec_stream", decl="void decode_mdec_stream(int frames_elapsed)"),
	Ident(addr=0x801581D0, name="play_mdec_stream", decl="void play_mdec_stream(char *filename, int speed, int start, int end)"),
	Ident(addr=0x8015826C, name="clear_mdec_queue", decl="void clear_mdec_queue()"),
	Ident(addr=0x80158298, name="StrClearVRAM", decl="void StrClearVRAM()"),
	Ident(addr=0x80158358, name="PlayFMVOverLay", decl="short PlayFMVOverLay(char *filename, int w, int h)"),
	Ident(addr=0x801583E0, name="LoPlayFMVOverLay", decl="void LoPlayFMVOverLay()"),
]

for f in funcs:
	ida_name.set_name(f.addr, f.name)
