from ida_name import set_name
from base_types import Ident

funcs = [
	# diabpsx/psxsrc/gameonly.cpp
	Ident(addr=0x80139BFC, name="GameOnlyTestRoutine__Fv", decl="void GameOnlyTestRoutine__Fv()"),

	# diabpsx/source/missiles.cpp
	Ident(addr=0x80139C04, name="GetDamageAmt__FiPiT1", decl="void GetDamageAmt__FiPiT1(int i, int *mind, int *maxd)"),
	Ident(addr=0x8013A1FC, name="CheckBlock__Fiiii", decl="int CheckBlock__Fiiii(int fx, int fy, int tx, int ty)"),
	Ident(addr=0x8013A2B0, name="FindClosest__Fiii", decl="int FindClosest__Fiii(int sx, int sy, int rad)"),
	Ident(addr=0x8013A43C, name="GetSpellLevel__Fii", decl="int GetSpellLevel__Fii(int id, int sn)"),
	Ident(addr=0x8013A4B0, name="GetDirection8__Fiiii", decl="int GetDirection8__Fiiii(int x1, int y1, int x2, int y2)"),
	Ident(addr=0x8013A6CC, name="GetDirection16__Fiiii", decl="int GetDirection16__Fiiii(int x1, int y1, int x2, int y2)"),
	Ident(addr=0x8013A8E8, name="DeleteMissile__Fii", decl="void DeleteMissile__Fii(int mi, int i)"),
	Ident(addr=0x8013A988, name="GetMissileVel__Fiiiiii", decl="void GetMissileVel__Fiiiiii(int i, int sx, int sy, int dx, int dy, int v)"),
	Ident(addr=0x8013AB44, name="PutMissile__Fi", decl="void PutMissile__Fi(int i)"),
	Ident(addr=0x8013ADA0, name="GetMissilePos__Fi", decl="void GetMissilePos__Fi(int i)"),
	Ident(addr=0x8013AED4, name="MoveMissilePos__Fi", decl="void MoveMissilePos__Fi(int i)"),
	Ident(addr=0x8013B04C, name="MonsterTrapHit__FiiiiiUc", decl="unsigned char MonsterTrapHit__FiiiiiUc(int m, int mindam, int maxdam, int dist, int t, int shift)"),
	Ident(addr=0x8013B3D0, name="MonsterMHit__FiiiiiiUc", decl="unsigned char MonsterMHit__FiiiiiiUc(int pnum, int m, int mindam, int maxdam, int dist, int t, int shift)"),
	Ident(addr=0x8013BB90, name="PlayerMHit__FiiiiiiUcUc", decl="unsigned char PlayerMHit__FiiiiiiUcUc(int pnum, int m, int dist, int mind, int maxd, int mtype, int shift, int earflag)"),
	Ident(addr=0x8013C5EC, name="Plr2PlrMHit__FiiiiiiUc", decl="unsigned char Plr2PlrMHit__FiiiiiiUc(int pnum, int p, int mindam, int maxdam, int dist, int mtype, int shift)"),
	Ident(addr=0x8013CD88, name="CheckMissileCol__FiiiUciiUcb", decl="void CheckMissileCol__FiiiUciiUcb(int i, int mindam, int maxdam, unsigned char shift, int mx, int my, int nodel, unknown HurtPlr)"),
	Ident(addr=0x8013D2B8, name="GetTableValue__FUci", decl="unsigned char GetTableValue__FUci(unsigned char code, int dir)"),
	Ident(addr=0x8013D34C, name="SetMissAnim__Fii", decl="void SetMissAnim__Fii(int mi, int animtype)"),
	Ident(addr=0x8013D424, name="SetMissDir__Fii", decl="void SetMissDir__Fii(int mi, int dir)"),
	Ident(addr=0x8013D470, name="AddLArrow__Fiiiiiicii", decl="void AddLArrow__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013D658, name="AddArrow__Fiiiiiicii", decl="void AddArrow__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013D818, name="GetVileMissPos__Fiii", decl="void GetVileMissPos__Fiii(int mi, int dx, int dy)"),
	Ident(addr=0x8013D954, name="AddRndTeleport__Fiiiiiicii", decl="void AddRndTeleport__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013DC98, name="AddFirebolt__Fiiiiiicii", decl="void AddFirebolt__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int micaster, int id, int dam)"),
	Ident(addr=0x8013DED0, name="AddMagmaball__Fiiiiiicii", decl="void AddMagmaball__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013DFEC, name="AddTeleport__Fiiiiiicii", decl="void AddTeleport__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013E228, name="AddLightball__Fiiiiiicii", decl="void AddLightball__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013E390, name="AddFirewall__Fiiiiiicii", decl="void AddFirewall__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013E588, name="AddFireball__Fiiiiiicii", decl="void AddFireball__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013E7F4, name="AddLightctrl__Fiiiiiicii", decl="void AddLightctrl__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013E8E0, name="AddLightning__Fiiiiiicii", decl="void AddLightning__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013EACC, name="AddMisexp__Fiiiiiicii", decl="void AddMisexp__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013ECF8, name="AddWeapexp__Fiiiiiicii", decl="void AddWeapexp__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013EDF8, name="CheckIfTrig__Fii", decl="unsigned char CheckIfTrig__Fii(int x, int y)"),
	Ident(addr=0x8013EFA0, name="AddTown__Fiiiiiicii", decl="void AddTown__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013F420, name="AddFlash__Fiiiiiicii", decl="void AddFlash__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013F64C, name="AddFlash2__Fiiiiiicii", decl="void AddFlash2__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013F83C, name="AddManashield__Fiiiiiicii", decl="void AddManashield__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013F910, name="AddFiremove__Fiiiiiicii", decl="void AddFiremove__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013FA70, name="AddGuardian__Fiiiiiicii", decl="void AddGuardian__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013FEE4, name="AddChain__Fiiiiiicii", decl="void AddChain__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x8013FF48, name="AddRhino__Fiiiiiicii", decl="void AddRhino__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x801400CC, name="AddFlare__Fiiiiiicii", decl="void AddFlare__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x801403DC, name="AddAcid__Fiiiiiicii", decl="void AddAcid__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x801404F0, name="AddAcidpud__Fiiiiiicii", decl="void AddAcidpud__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x801405D4, name="AddStone__Fiiiiiicii", decl="void AddStone__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80140904, name="AddGolem__Fiiiiiicii", decl="void AddGolem__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80140C44, name="AddBoom__Fiiiiiicii", decl="void AddBoom__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80140CE8, name="AddHeal__Fiiiiiicii", decl="void AddHeal__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80140F14, name="AddHealOther__Fiiiiiicii", decl="void AddHealOther__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80140F84, name="AddElement__Fiiiiiicii", decl="void AddElement__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x801411B4, name="AddIdentify__Fiiiiiicii", decl="void AddIdentify__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80141258, name="AddFirewallC__Fiiiiiicii", decl="void AddFirewallC__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80141518, name="AddInfra__Fiiiiiicii", decl="void AddInfra__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80141624, name="AddWave__Fiiiiiicii", decl="void AddWave__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x801416B0, name="AddNova__Fiiiiiicii", decl="void AddNova__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x801418C0, name="AddRepair__Fiiiiiicii", decl="void AddRepair__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80141978, name="AddRecharge__Fiiiiiicii", decl="void AddRecharge__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80141A30, name="AddDisarm__Fiiiiiicii", decl="void AddDisarm__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80141AA0, name="AddApoca__Fiiiiiicii", decl="void AddApoca__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80141D08, name="AddFlame__Fiiiiiicii", decl="void AddFlame__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int seqno)"),
	Ident(addr=0x80141F40, name="AddFlamec__Fiiiiiicii", decl="void AddFlamec__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80142038, name="AddCbolt__Fiiiiiicii", decl="void AddCbolt__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int micaster, int id, int dam)"),
	Ident(addr=0x80142248, name="AddHbolt__Fiiiiiicii", decl="void AddHbolt__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int micaster, int id, int dam)"),
	Ident(addr=0x80142414, name="AddResurrect__Fiiiiiicii", decl="void AddResurrect__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80142490, name="AddResurrectBeam__Fiiiiiicii", decl="void AddResurrectBeam__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80142520, name="AddTelekinesis__Fiiiiiicii", decl="void AddTelekinesis__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80142590, name="AddBoneSpirit__Fiiiiiicii", decl="void AddBoneSpirit__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80142794, name="AddRportal__Fiiiiiicii", decl="void AddRportal__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x801428C0, name="AddDiabApoca__Fiiiiiicii", decl="void AddDiabApoca__Fiiiiiicii(int mi, int sx, int sy, int dx, int dy, int midir, int mienemy, int id, int dam)"),
	Ident(addr=0x80142A04, name="AddMissile__Fiiiiiiciii", decl="int AddMissile__Fiiiiiiciii(int sx, int sy, int v1, int v2, int midir, int mitype, int micaster, int id, int v3, int spllvl)"),
	Ident(addr=0x80142E90, name="Sentfire__Fiii", decl="int Sentfire__Fiii(int i, int sx, int sy)"),
	Ident(addr=0x80143078, name="MI_Dummy__Fi", decl="void MI_Dummy__Fi(int i)"),
	Ident(addr=0x80143080, name="MI_Golem__Fi", decl="void MI_Golem__Fi(int i)"),
	Ident(addr=0x801432FC, name="MI_SetManashield__Fi", decl="void MI_SetManashield__Fi(int i)"),
	Ident(addr=0x80143340, name="MI_LArrow__Fi", decl="void MI_LArrow__Fi(int i)"),
	Ident(addr=0x80143B54, name="MI_Arrow__Fi", decl="void MI_Arrow__Fi(int i)"),
	Ident(addr=0x80143D98, name="MI_Firebolt__Fi", decl="void MI_Firebolt__Fi(int i)"),
	Ident(addr=0x801444AC, name="MI_Lightball__Fi", decl="void MI_Lightball__Fi(int i)"),
	Ident(addr=0x80144764, name="MI_Acidpud__Fi", decl="void MI_Acidpud__Fi(int i)"),
	Ident(addr=0x80144890, name="MI_Firewall__Fi", decl="void MI_Firewall__Fi(int i)"),
	Ident(addr=0x80144BAC, name="MI_Fireball__Fi", decl="void MI_Fireball__Fi(int i)"),
	Ident(addr=0x80145528, name="MI_Lightctrl__Fi", decl="void MI_Lightctrl__Fi(int i)"),
	Ident(addr=0x801458E0, name="MI_Lightning__Fi", decl="void MI_Lightning__Fi(int i)"),
	Ident(addr=0x801459E0, name="MI_Town__Fi", decl="void MI_Town__Fi(int i)"),
	Ident(addr=0x80145D38, name="MI_Flash__Fi", decl="void MI_Flash__Fi(int i)"),
	Ident(addr=0x801460AC, name="MI_Flash2__Fi", decl="void MI_Flash2__Fi(int i)"),
	Ident(addr=0x80146288, name="MI_Manashield__Fi", decl="void MI_Manashield__Fi(int i)"),
	Ident(addr=0x80146588, name="MI_Firemove__Fi", decl="void MI_Firemove__Fi(int i)"),
	Ident(addr=0x80146828, name="MI_Guardian__Fi", decl="void MI_Guardian__Fi(int i)"),
	Ident(addr=0x80146AE0, name="MI_Chain__Fi", decl="void MI_Chain__Fi(int i)"),
	Ident(addr=0x80146D48, name="MI_Weapexp__Fi", decl="void MI_Weapexp__Fi(int i)"),
	Ident(addr=0x801470A4, name="MI_Misexp__Fi", decl="void MI_Misexp__Fi(int i)"),
	Ident(addr=0x801473C4, name="MI_Acidsplat__Fi", decl="void MI_Acidsplat__Fi(int i)"),
	Ident(addr=0x80147570, name="MI_Teleport__Fi", decl="void MI_Teleport__Fi(int i)"),
	Ident(addr=0x801478DC, name="MI_Stone__Fi", decl="void MI_Stone__Fi(int i)"),
	Ident(addr=0x80147AB8, name="RemoveStoneMissiles__Fiii", decl="void RemoveStoneMissiles__Fiii(int mon, int mx, int my)"),
	Ident(addr=0x80147B40, name="MI_Boom__Fi", decl="void MI_Boom__Fi(int i)"),
	Ident(addr=0x80147C44, name="MI_Rhino__Fi", decl="void MI_Rhino__Fi(int i)"),
	Ident(addr=0x80148054, name="MI_FirewallC__Fi", decl="void MI_FirewallC__Fi(int i)"),
	Ident(addr=0x80148288, name="MI_Infra__Fi", decl="void MI_Infra__Fi(int i)"),
	Ident(addr=0x80148348, name="MI_Apoca__Fi", decl="void MI_Apoca__Fi(int i)"),
	Ident(addr=0x80148600, name="MI_Wave__Fi", decl="void MI_Wave__Fi(int i)"),
	Ident(addr=0x80148A9C, name="MI_Nova__Fi", decl="void MI_Nova__Fi(int i)"),
	Ident(addr=0x80148D78, name="MI_Flame__Fi", decl="void MI_Flame__Fi(int i)"),
	Ident(addr=0x80148F94, name="MI_Flamec__Fi", decl="void MI_Flamec__Fi(int i)"),
	Ident(addr=0x80149210, name="MI_Cbolt__Fi", decl="void MI_Cbolt__Fi(int i)"),
	Ident(addr=0x80149564, name="MI_Hbolt__Fi", decl="void MI_Hbolt__Fi(int i)"),
	Ident(addr=0x80149890, name="MI_Element__Fi", decl="void MI_Element__Fi(int i)"),
	Ident(addr=0x80149FAC, name="MI_Bonespirit__Fi", decl="void MI_Bonespirit__Fi(int i)"),
	Ident(addr=0x8014A3E0, name="MI_ResurrectBeam__Fi", decl="void MI_ResurrectBeam__Fi(int i)"),
	Ident(addr=0x8014A458, name="MI_Rportal__Fi", decl="void MI_Rportal__Fi(int i)"),
	Ident(addr=0x8014A694, name="ProcessMissiles__Fv", decl="void ProcessMissiles__Fv()"),
	Ident(addr=0x8014AAC0, name="ClearMissileSpot__Fi", decl="void ClearMissileSpot__Fi(int mi)"),

	# diabpsx/source/monster.cpp
	Ident(addr=0x8014AB74, name="DeleteMonster__Fi", decl="void DeleteMonster__Fi(int i)"),
	Ident(addr=0x8014ABAC, name="M_GetDir__Fi", decl="int M_GetDir__Fi(int i)"),
	Ident(addr=0x8014AC10, name="M_StartDelay__Fii", decl="void M_StartDelay__Fii(int i, int len)"),
	Ident(addr=0x8014AC60, name="M_StartRAttack__Fiii", decl="void M_StartRAttack__Fiii(int i, int missile_type, int dam)"),
	Ident(addr=0x8014AD80, name="M_StartRSpAttack__Fiii", decl="void M_StartRSpAttack__Fiii(int i, int missile_type, int dam)"),
	Ident(addr=0x8014AEF4, name="M_StartSpAttack__Fi", decl="void M_StartSpAttack__Fi(int i)"),
	Ident(addr=0x8014AFE4, name="M_StartEat__Fi", decl="void M_StartEat__Fi(int i)"),
	Ident(addr=0x8014B0BC, name="M_GetKnockback__Fii", decl="void M_GetKnockback__Fii(int i, int d)"),
	Ident(addr=0x8014B2D8, name="M_StartHit__Fiii", decl="void M_StartHit__Fiii(int i, int pnum, int dam)"),
	Ident(addr=0x8014B5C0, name="M_DiabloDeath__FiUci", decl="void M_DiabloDeath__FiUci(int i, unsigned char sendmsg, int pnum)"),
	Ident(addr=0x8014B8E8, name="M2MStartHit__Fiii", decl="void M2MStartHit__Fiii(int mid, int i, int dam)"),
	Ident(addr=0x8014BBA4, name="MonstStartKill__FiiUc", decl="void MonstStartKill__FiiUc(int i, int pnum, unsigned char sendmsg)"),
	Ident(addr=0x8014BEC0, name="SyncMonstStartKill__FiiUc", decl="void SyncMonstStartKill__FiiUc(int i, int pnum, unsigned char sendmsg)"),
	Ident(addr=0x8014C010, name="M2MStartKill__Fii", decl="void M2MStartKill__Fii(int i, int mid)"),
	Ident(addr=0x8014C3D8, name="M_StartKill__Fii", decl="void M_StartKill__Fii(int i, int pnum)"),
	Ident(addr=0x8014C4E0, name="M_SyncStartKill__Fiiii", decl="void M_SyncStartKill__Fiiii(int i, int x, int y, int pnum)"),
	Ident(addr=0x8014C5F0, name="M_StartFadein__FiiUc", decl="void M_StartFadein__FiiUc(int i, int md, unsigned char backwards)"),
	Ident(addr=0x8014C74C, name="M_StartFadeout__FiiUc", decl="void M_StartFadeout__FiiUc(int i, int md, unsigned char backwards)"),
	Ident(addr=0x8014C89C, name="M_StartHeal__Fi", decl="void M_StartHeal__Fi(int i)"),
	Ident(addr=0x8014C928, name="M_ChangeLightOffset__Fi", decl="void M_ChangeLightOffset__Fi(int monst)"),
	Ident(addr=0x8014CA90, name="M_DoStand__Fi", decl="int M_DoStand__Fi(int i)"),
	Ident(addr=0x8014CAF0, name="M_DoWalk__Fi", decl="int M_DoWalk__Fi(int i)"),
	Ident(addr=0x8014CD60, name="M_DoWalk2__Fi", decl="int M_DoWalk2__Fi(int i)"),
	Ident(addr=0x8014CF4C, name="M_DoWalk3__Fi", decl="int M_DoWalk3__Fi(int i)"),
	Ident(addr=0x8014D1F0, name="M_TryM2MHit__Fiiiii", decl="void M_TryM2MHit__Fiiiii(int i, int mid, int hper, int mind, int maxd)"),
	Ident(addr=0x8014D428, name="M_TryH2HHit__Fiiiii", decl="void M_TryH2HHit__Fiiiii(int i, int pnum, int Hit, int MinDam, int MaxDam)"),
	Ident(addr=0x8014DA3C, name="M_DoAttack__Fi", decl="int M_DoAttack__Fi(int i)"),
	Ident(addr=0x8014DBE8, name="M_DoRAttack__Fi", decl="int M_DoRAttack__Fi(int i)"),
	Ident(addr=0x8014DD70, name="M_DoRSpAttack__Fi", decl="int M_DoRSpAttack__Fi(int i)"),
	Ident(addr=0x8014DF78, name="M_DoSAttack__Fi", decl="int M_DoSAttack__Fi(int i)"),
	Ident(addr=0x8014E054, name="M_DoFadein__Fi", decl="int M_DoFadein__Fi(int i)"),
	Ident(addr=0x8014E134, name="M_DoFadeout__Fi", decl="int M_DoFadeout__Fi(int i)"),
	Ident(addr=0x8014E260, name="M_DoHeal__Fi", decl="int M_DoHeal__Fi(int i)"),
	Ident(addr=0x8014E2FC, name="M_DoTalk__Fi", decl="int M_DoTalk__Fi(int i)"),
	Ident(addr=0x8014E8A0, name="M_Teleport__Fi", decl="void M_Teleport__Fi(int i)"),
	Ident(addr=0x8014EAB4, name="M_DoGotHit__Fi", decl="int M_DoGotHit__Fi(int i)"),
	Ident(addr=0x8014EB1C, name="DoEnding__Fi", decl="void DoEnding__Fi(int p)"),
	Ident(addr=0x8014EBC4, name="PrepDoEnding__Fi", decl="void PrepDoEnding__Fi(int pnum)"),
	Ident(addr=0x8014ED0C, name="M_DoDeath__Fi", decl="int M_DoDeath__Fi(int i)"),
	Ident(addr=0x8014EED0, name="M_DoSpStand__Fi", decl="int M_DoSpStand__Fi(int i)"),
	Ident(addr=0x8014EF7C, name="M_DoDelay__Fi", decl="int M_DoDelay__Fi(int i)"),
	Ident(addr=0x8014F090, name="M_DoStone__Fi", decl="int M_DoStone__Fi(int i)"),
	Ident(addr=0x8014F10C, name="M_WalkDir__Fii", decl="void M_WalkDir__Fii(int i, int md)"),
	Ident(addr=0x8014F33C, name="GroupUnity__Fi", decl="void GroupUnity__Fi(int i)"),
	Ident(addr=0x8014F750, name="M_CallWalk__Fii", decl="unsigned char M_CallWalk__Fii(int i, int md)"),
	Ident(addr=0x8014F8F0, name="M_CallWalk2__Fii", decl="unsigned char M_CallWalk2__Fii(int i, int md)"),
	Ident(addr=0x8014F9E8, name="M_DumbWalk__Fii", decl="unsigned char M_DumbWalk__Fii(int i, int md)"),
	Ident(addr=0x8014FA3C, name="M_RoundWalk__FiiRi", decl="unsigned char M_RoundWalk__FiiRi(int i, int md, int *dir)"),
	Ident(addr=0x8014FB88, name="MAI_Zombie__Fi", decl="void MAI_Zombie__Fi(int i)"),
	Ident(addr=0x8014FD88, name="MAI_SkelSd__Fi", decl="void MAI_SkelSd__Fi(int i)"),
	Ident(addr=0x8014FF38, name="MAI_Snake__Fi", decl="void MAI_Snake__Fi(int i)"),
	Ident(addr=0x80150334, name="MAI_Bat__Fi", decl="void MAI_Bat__Fi(int i)"),
	Ident(addr=0x801506E8, name="MAI_SkelBow__Fi", decl="void MAI_SkelBow__Fi(int i)"),
	Ident(addr=0x801508DC, name="MAI_Fat__Fi", decl="void MAI_Fat__Fi(int i)"),
	Ident(addr=0x80150AA4, name="MAI_Sneak__Fi", decl="void MAI_Sneak__Fi(int i)"),
	Ident(addr=0x80150E80, name="MAI_Fireman__Fi", decl="void MAI_Fireman__Fi(int i)"),
	Ident(addr=0x80151184, name="MAI_Fallen__Fi", decl="void MAI_Fallen__Fi(int i)"),
	Ident(addr=0x80151498, name="MAI_Cleaver__Fi", decl="void MAI_Cleaver__Fi(int i)"),
	Ident(addr=0x8015159C, name="MAI_Round__FiUc", decl="void MAI_Round__FiUc(int i, unsigned char special)"),
	Ident(addr=0x801519DC, name="MAI_GoatMc__Fi", decl="void MAI_GoatMc__Fi(int i)"),
	Ident(addr=0x801519FC, name="MAI_Ranged__FiiUc", decl="void MAI_Ranged__FiiUc(int i, int missile_type, unsigned char special)"),
	Ident(addr=0x80151C20, name="MAI_GoatBow__Fi", decl="void MAI_GoatBow__Fi(int i)"),
	Ident(addr=0x80151C44, name="MAI_Succ__Fi", decl="void MAI_Succ__Fi(int i)"),
	Ident(addr=0x80151C68, name="MAI_AcidUniq__Fi", decl="void MAI_AcidUniq__Fi(int i)"),
	Ident(addr=0x80151C8C, name="MAI_Scav__Fi", decl="void MAI_Scav__Fi(int i)"),
	Ident(addr=0x80152050, name="MAI_Garg__Fi", decl="void MAI_Garg__Fi(int i)"),
	Ident(addr=0x80152230, name="MAI_RoundRanged__FiiUciUc", decl="void MAI_RoundRanged__FiiUciUc(int i, int missile_type, unsigned char checkdoors, int dam, int lessmissiles)"),
	Ident(addr=0x80152720, name="MAI_Magma__Fi", decl="void MAI_Magma__Fi(int i)"),
	Ident(addr=0x8015274C, name="MAI_Storm__Fi", decl="void MAI_Storm__Fi(int i)"),
	Ident(addr=0x80152778, name="MAI_Acid__Fi", decl="void MAI_Acid__Fi(int i)"),
	Ident(addr=0x801527A8, name="MAI_Diablo__Fi", decl="void MAI_Diablo__Fi(int i)"),
	Ident(addr=0x801527D4, name="MAI_RR2__Fiii", decl="void MAI_RR2__Fiii(int i, int mistype, int dam)"),
	Ident(addr=0x80152CB8, name="MAI_Mega__Fi", decl="void MAI_Mega__Fi(int i)"),
	Ident(addr=0x80152CDC, name="MAI_SkelKing__Fi", decl="void MAI_SkelKing__Fi(int i)"),
	Ident(addr=0x80153218, name="MAI_Rhino__Fi", decl="void MAI_Rhino__Fi(int i)"),
	Ident(addr=0x801536D4, name="MAI_Counselor__Fi", decl="void MAI_Counselor__Fi(int i)"),
	Ident(addr=0x80153B70, name="MAI_Garbud__Fi", decl="void MAI_Garbud__Fi(int i)"),
	Ident(addr=0x80153D80, name="MAI_Zhar__Fi", decl="void MAI_Zhar__Fi(int i)"),
	Ident(addr=0x80153F7C, name="MAI_SnotSpil__Fi", decl="void MAI_SnotSpil__Fi(int i)"),
	Ident(addr=0x801541CC, name="MAI_Lazurus__Fi", decl="void MAI_Lazurus__Fi(int i)"),
	Ident(addr=0x80154470, name="MAI_Lazhelp__Fi", decl="void MAI_Lazhelp__Fi(int i)"),
	Ident(addr=0x801545A8, name="MAI_Lachdanan__Fi", decl="void MAI_Lachdanan__Fi(int i)"),
	Ident(addr=0x80154758, name="MAI_Warlord__Fi", decl="void MAI_Warlord__Fi(int i)"),
	Ident(addr=0x801548C0, name="DeleteMonsterList__Fv", decl="void DeleteMonsterList__Fv()"),
	Ident(addr=0x801549E4, name="ProcessMonsters__Fv", decl="void ProcessMonsters__Fv()"),
	Ident(addr=0x80154FAC, name="DirOK__Fii", decl="unsigned char DirOK__Fii(int i, int mdir)"),
	Ident(addr=0x80155158, name="PosOkMissile__Fii", decl="unsigned char PosOkMissile__Fii(int x, int y)"),
	Ident(addr=0x801551D0, name="CheckNoSolid__Fii", decl="unsigned char CheckNoSolid__Fii(int x, int y)"),
	Ident(addr=0x801551F0, name="LineClearF__FPFii_Uciiii", decl="unsigned char LineClearF__FPFii_Uciiii(unsigned char (*Clear)(), int x1, int y1, int x2, int y2)"),
	Ident(addr=0x80155478, name="LineClear__Fiiii", decl="unsigned char LineClear__Fiiii(int x1, int y1, int x2, int y2)"),
	Ident(addr=0x801554B8, name="LineClearF1__FPFiii_Uciiiii", decl="unsigned char LineClearF1__FPFiii_Uciiiii(unsigned char (*Clear)(), int monst, int x1, int y1, int x2, int y2)"),
	Ident(addr=0x8015574C, name="M_FallenFear__Fii", decl="void M_FallenFear__Fii(int x, int y)"),
	Ident(addr=0x80155934, name="PrintMonstHistory__Fi", decl="void PrintMonstHistory__Fi(int mt)"),
	Ident(addr=0x80155BB8, name="PrintUniqueHistory__Fv", decl="void PrintUniqueHistory__Fv()"),
	Ident(addr=0x80155CE4, name="MissToMonst__Fiii", decl="void MissToMonst__Fiii(int i, int x, int y)"),
	Ident(addr=0x801561B0, name="PosOkMonst3__Fiii", decl="unsigned char PosOkMonst3__Fiii(int i, int x, int y)"),
	Ident(addr=0x8015648C, name="M_SpawnSkel__Fiii", decl="int M_SpawnSkel__Fiii(int x, int y, int dir)"),
	Ident(addr=0x801565DC, name="TalktoMonster__Fi", decl="void TalktoMonster__Fi(int i)"),
	Ident(addr=0x8015671C, name="SpawnGolum__Fiiii", decl="void SpawnGolum__Fiiii(int i, int x, int y, int mi)"),
	Ident(addr=0x8015694C, name="CanTalkToMonst__Fi", decl="unsigned char CanTalkToMonst__Fi(int m)"),
	Ident(addr=0x8015698C, name="CheckMonsterHit__FiRUc", decl="unsigned char CheckMonsterHit__FiRUc(int m, unsigned char *ret)"),
	Ident(addr=0x80156A68, name="gSameRoom__Fii", decl="unknown gSameRoom__Fii(int m, int i)"),
	Ident(addr=0x80156B00, name="MAI_Golum__Fi", decl="void MAI_Golum__Fi(int i)"),
	Ident(addr=0x8015702C, name="M_StartAttack__Fi", decl="void M_StartAttack__Fi(int i)"),
	Ident(addr=0x8015711C, name="M_StartWalk__Fiiiiii", decl="void M_StartWalk__Fiiiiii(int i, int xvel, int yvel, int xadd, int yadd, int EndDir)"),

	# diabpsx/source/inv.cpp
	Ident(addr=0x80157274, name="FreeInvGFX__Fv", decl="void FreeInvGFX__Fv()"),
	Ident(addr=0x8015727C, name="InvDrawSlot__Fiii", decl="void InvDrawSlot__Fiii(int X, int Y, int Frame)"),
	Ident(addr=0x80157300, name="InvDrawSlotBack__FiiiiUc", decl="void InvDrawSlotBack__FiiiiUc(int X, int Y, int W, int H, int Flag)"),
	Ident(addr=0x801575B8, name="InvDrawItem__FiiiUci", decl="void InvDrawItem__FiiiUci(int ItemX, int ItemY, int ItemNo, unsigned char StatFlag, int TransFlag)"),
	Ident(addr=0x80157688, name="InvDrawSlots__Fv", decl="void InvDrawSlots__Fv()"),
	Ident(addr=0x801579A0, name="PrintStat__FiiPcUc", decl="void PrintStat__FiiPcUc(int Y, int Txt0, char *Txt1, unsigned char Col)"),
	Ident(addr=0x80157A6C, name="DrawInvStats__Fv", decl="void DrawInvStats__Fv()"),
	Ident(addr=0x80158588, name="DrawInvBack__Fv", decl="void DrawInvBack__Fv()"),
	Ident(addr=0x80158634, name="DrawInvCursor__Fv", decl="void DrawInvCursor__Fv()"),
	Ident(addr=0x80158C00, name="DrawInvMsg__Fv", decl="void DrawInvMsg__Fv()"),
	Ident(addr=0x80158DCC, name="DrawInvHelpTxt__Fv", decl="void DrawInvHelpTxt__Fv()"),
	Ident(addr=0x801590B4, name="DrawInv__Fv", decl="void DrawInv__Fv()"),
	Ident(addr=0x801590FC, name="DrawInvTSK__FP4TASK", decl="void DrawInvTSK__FP4TASK(struct TASK *T)"),
	Ident(addr=0x80159714, name="DoThatDrawInv__Fv", decl="void DoThatDrawInv__Fv()"),
	Ident(addr=0x80159F24, name="AutoPlace__FiiiiUc", decl="unsigned char AutoPlace__FiiiiUc(int pnum, int ii, int sx, int sy, int saveflag)"),
	Ident(addr=0x8015A24C, name="SpecialAutoPlace__FiiiiUc", decl="unsigned char SpecialAutoPlace__FiiiiUc(int pnum, int ii, int sx, int sy, int saveflag)"),
	Ident(addr=0x8015A5F0, name="GoldAutoPlace__Fi", decl="unsigned char GoldAutoPlace__Fi(int pnum)"),
	Ident(addr=0x8015AAC8, name="WeaponAutoPlace__Fi", decl="unsigned char WeaponAutoPlace__Fi(int pnum)"),
	Ident(addr=0x8015AD5C, name="SwapItem__FP10ItemStructT0", decl="int SwapItem__FP10ItemStructT0(struct ItemStruct *a, struct ItemStruct *b)"),
	Ident(addr=0x8015AE70, name="CheckInvPaste__Fiii", decl="void CheckInvPaste__Fiii(int pnum, int mx, int my)"),
	Ident(addr=0x8015CBF8, name="CheckInvCut__Fiii", decl="void CheckInvCut__Fiii(int pnum, int mx, int my)"),
	Ident(addr=0x8015D6FC, name="RemoveInvItem__Fii", decl="void RemoveInvItem__Fii(int pnum, int iv)"),
	Ident(addr=0x8015D9AC, name="RemoveSpdBarItem__Fii", decl="void RemoveSpdBarItem__Fii(int pnum, int iv)"),
	Ident(addr=0x8015DAA0, name="CheckInvScrn__Fv", decl="void CheckInvScrn__Fv()"),
	Ident(addr=0x8015DB18, name="CheckItemStats__Fi", decl="void CheckItemStats__Fi(int pnum)"),
	Ident(addr=0x8015DB9C, name="CheckBookLevel__Fi", decl="void CheckBookLevel__Fi(int pnum)"),
	Ident(addr=0x8015DCD0, name="CheckQuestItem__Fi", decl="void CheckQuestItem__Fi(int pnum)"),
	Ident(addr=0x8015E180, name="InvGetItem__Fii", decl="void InvGetItem__Fii(int pnum, int ii)"),
	Ident(addr=0x8015E45C, name="AutoGetItem__Fii", decl="void AutoGetItem__Fii(int pnum, int ii)"),
	Ident(addr=0x8015EEB8, name="SyncGetItem__FiiiUsi", decl="void SyncGetItem__FiiiUsi(int x, int y, int idx, unsigned short ci, int iseed)"),
	Ident(addr=0x8015F020, name="TryInvPut__Fv", decl="unsigned char TryInvPut__Fv()"),
	Ident(addr=0x8015F16C, name="InvPutItem__Fiii", decl="int InvPutItem__Fiii(int pnum, int x, int y)"),
	Ident(addr=0x8015F504, name="SyncPutItem__FiiiiUsiUciiiiiUl", decl="int SyncPutItem__FiiiiUsiUciiiiiUl(int pnum, int x, int y, int idx, int icreateinfo, int iseed, int Id, int dur, int mdur, int ch, int mch, int ivalue, unsigned long ibuff)"),
	Ident(addr=0x8015FA64, name="CheckInvHLight__Fv", decl="char CheckInvHLight__Fv()"),
	Ident(addr=0x8015FDFC, name="RemoveScroll__Fi", decl="void RemoveScroll__Fi(int pnum)"),
	Ident(addr=0x8015FFE0, name="UseScroll__Fv", decl="unsigned char UseScroll__Fv()"),
	Ident(addr=0x80160248, name="UseStaffCharge__FP12PlayerStruct", decl="void UseStaffCharge__FP12PlayerStruct(struct PlayerStruct *ptrplr)"),
	Ident(addr=0x801602AC, name="UseStaff__Fv", decl="unsigned char UseStaff__Fv()"),
	Ident(addr=0x8016036C, name="StartGoldDrop__Fv", decl="void StartGoldDrop__Fv()"),
	Ident(addr=0x80160470, name="UseInvItem__Fii", decl="unsigned char UseInvItem__Fii(int pnum, int cii)"),
	Ident(addr=0x80160A34, name="DoTelekinesis__Fv", decl="void DoTelekinesis__Fv()"),
	Ident(addr=0x80160B64, name="CalculateGold__Fi", decl="long CalculateGold__Fi(int pnum)"),
	Ident(addr=0x80160C9C, name="DropItemBeforeTrig__Fv", decl="unsigned char DropItemBeforeTrig__Fv()"),
	Ident(addr=0x80160CF4, name="ControlInv__Fv", decl="void ControlInv__Fv()"),
	Ident(addr=0x801610B0, name="InvGetItemWH__Fi", decl="void InvGetItemWH__Fi(int Pos)"),
	Ident(addr=0x801611A8, name="InvAlignObject__Fv", decl="void InvAlignObject__Fv()"),
	Ident(addr=0x8016135C, name="InvSetItemCurs__Fv", decl="void InvSetItemCurs__Fv()"),
	Ident(addr=0x801614FC, name="InvMoveCursLeft__Fv", decl="void InvMoveCursLeft__Fv()"),
	Ident(addr=0x801616A4, name="InvMoveCursRight__Fv", decl="void InvMoveCursRight__Fv()"),
	Ident(addr=0x80161958, name="InvMoveCursUp__Fv", decl="void InvMoveCursUp__Fv()"),
	Ident(addr=0x80161B50, name="InvMoveCursDown__Fv", decl="void InvMoveCursDown__Fv()"),

	# diabpsx/source/automap.cpp
	Ident(addr=0x80161F58, name="StartAutomap__Fv", decl="void StartAutomap__Fv()"),
	Ident(addr=0x80161F68, name="AutomapUp__Fv", decl="void AutomapUp__Fv()"),
	Ident(addr=0x80161F88, name="AutomapDown__Fv", decl="void AutomapDown__Fv()"),
	Ident(addr=0x80161FA8, name="AutomapLeft__Fv", decl="void AutomapLeft__Fv()"),
	Ident(addr=0x80161FC8, name="AutomapRight__Fv", decl="void AutomapRight__Fv()"),
	Ident(addr=0x80161FE8, name="AMGetLine__FUcUcUc", decl="struct LINE_F2* AMGetLine__FUcUcUc(unsigned char R, unsigned char G, unsigned char B)"),
	Ident(addr=0x801620A0, name="AmDrawPlayer__Fiiiii", decl="void AmDrawPlayer__Fiiiii(int x0, int y0, int x1, int y1, int PNum)"),
	Ident(addr=0x80162124, name="DrawAutomapPlr__Fv", decl="void DrawAutomapPlr__Fv()"),
	Ident(addr=0x80162490, name="DrawAutoMapVertDoor__Fii", decl="void DrawAutoMapVertDoor__Fii(int X, int Y)"),
	Ident(addr=0x8016264C, name="DrawAutoMapHorzDoor__Fii", decl="void DrawAutoMapHorzDoor__Fii(int X, int Y)"),
	Ident(addr=0x8016280C, name="DrawAutoMapVertGrate__Fii", decl="void DrawAutoMapVertGrate__Fii(int X, int Y)"),
	Ident(addr=0x801628A4, name="DrawAutoMapHorzGrate__Fii", decl="void DrawAutoMapHorzGrate__Fii(int X, int Y)"),
	Ident(addr=0x8016293C, name="DrawAutoMapSquare__Fii", decl="void DrawAutoMapSquare__Fii(int X, int Y)"),
	Ident(addr=0x80162A70, name="DrawVertArch__Fii", decl="void DrawVertArch__Fii(int X, int Y)"),
	Ident(addr=0x80162BA4, name="DrawHorzArch__Fii", decl="void DrawHorzArch__Fii(int X, int Y)"),
	Ident(addr=0x80162CD8, name="DrawAutoMapStairs__Fii", decl="void DrawAutoMapStairs__Fii(int X, int Y)"),
	Ident(addr=0x80162E50, name="DrawAutomap__Fv", decl="void DrawAutomap__Fv()"),
]

for f in funcs:
	ida_name.set_name(f.addr, f.name)
